/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package student;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author diane
 */
public class displaystudent extends javax.swing.JFrame {

    /**
     * Creates new form displaystudent
     */
    public displaystudent() {
        initComponents();
    }
Connection con;
    Statement pst;
    ResultSet result;
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        delete = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        fname = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        lname = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        age = new javax.swing.JTextField();
        add = new javax.swing.JButton();
        id = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("List of Students");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 40, 180, 40));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "ID", "FIRSTNAME", "LASTNAME", "AGE", "GENDER"
            }
        ));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 110, 710, 120));

        jButton1.setText("Show Students");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 280, -1, -1));

        delete.setText("Delete");
        delete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteActionPerformed(evt);
            }
        });
        getContentPane().add(delete, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 330, -1, -1));

        jButton2.setText("Update");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 370, -1, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel3.setText("Firstname:");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 280, -1, -1));
        getContentPane().add(fname, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 270, 310, 40));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel4.setText("Lastname:");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 340, -1, -1));
        getContentPane().add(lname, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 330, 310, 40));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel5.setText("Age:");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 390, -1, -1));
        getContentPane().add(age, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 390, 310, 40));

        add.setText("Add New");
        getContentPane().add(add, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 420, -1, -1));

        id.setEditable(false);
        getContentPane().add(id, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 240, 20, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        try {
                //Creating Connection Object
                Connection con=DriverManager.getConnection("jdbc:mysql://localhost:3306/ishimwe_diane","root","");
                //Preapared Statement
                String sql="SELECT * FROM student";
                PreparedStatement pst=con.prepareStatement(sql);
                ResultSet rs=pst.executeQuery(sql);
                DefaultTableModel model=(DefaultTableModel) jTable1.getModel();
                model.setRowCount(0);
                while(rs.next())
                {
                    model.addRow(new String[] {rs.getString("sid"),rs.getString("fname"),rs.getString("lname"),rs.getString("age"),rs.getString("gender")});
                }
                //Specifying the values of it's parameter
                
              //Checking for the Password match
               
                } catch (SQLException e) {
               System.out.println("Error: " +e.getMessage());
                }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void deleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteActionPerformed
        // TODO add your handling code here:
  DefaultTableModel tabl=(DefaultTableModel)jTable1.getModel();
        int selectIndex = jTable1.getSelectedRow();
        int id = Integer.parseInt(tabl.getValueAt(selectIndex,0).toString());
        
        try {
            Connection con=DriverManager.getConnection("jdbc:mysql://localhost:3306/ishimwe_diane","root","");
                //Preapared Statement
                String sql="DELETE FROM student where sid=?";
                PreparedStatement pst=con.prepareStatement(sql);
            
            pst.setInt(1, id);
            
            int k=pst.executeUpdate();
            
            if(k==1){
                JOptionPane.showMessageDialog(this,"Data is Deleted Successifully");
                
                 
            }
            
            
            
        } catch (SQLException ex) {
            Logger.getLogger(displaystudent.class.getName()).log(Level.SEVERE, null, ex);
        
                       
    }//GEN-LAST:event_jButton1ActionPerformed
    }//GEN-LAST:event_deleteActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
         DefaultTableModel table2=(DefaultTableModel)jTable1.getModel();
        int select=jTable1.getSelectedRow();
        int sid=Integer.parseInt(table2.getValueAt(select, 0).toString());
        
        //String mi=id.getText();
        String mname=fname.getText();
        String mquantity=lname.getText();
        String mfg=age.getText();
       
        
        
        
        
        try {
            Connection con=DriverManager.getConnection("jdbc:mysql://localhost:3306/ishimwe_diane","root","");
             String sql="UPDATE student SET fname=?,lname=?,age=? WHERE sid=?";
             
            PreparedStatement pst=con.prepareStatement(sql);
            pst.setString(1, mname);
            pst.setString(2, mquantity);
            pst.setString(3, mfg);
            pst.setInt(4, sid);
             
            
            int m=pst.executeUpdate();
            
            if(m==1){
                JOptionPane.showMessageDialog(this, "Update Saved Successifully");
            }
            
            else{
                JOptionPane.showMessageDialog(this,"You Made An Error");
                fname.setText("");
                lname.setText("");
                age.setText("");
                
               //mednamef1.requestFocus();
            }
        }
        
        catch (SQLException ex) {
            JOptionPane.showMessageDialog(this,"kabaye");
           Logger.getLogger(displaystudent.class.getName()).log(Level.SEVERE, null, ex);
        
    
                                         
    }//GEN-LAST:event_UPDATEActionPerformed
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        // TODO add your handling code here:
      try {
          int row= jTable1.getSelectedRow();
        String tableco=jTable1.getModel().getValueAt(row,0).toString();

        String myquerry="select*from student where sid="+tableco+"";
       
            Connection con=DriverManager.getConnection("jdbc:mysql://localhost:3306/ishimwe_diane","root","");
            pst=con.prepareStatement(myquerry);

            result=pst.executeQuery(myquerry);
            if(result.next()){
                int idd=result.getInt("sid");
                String name=result.getString("fname");
                String quantity=result.getString("lname");
                String mfg=result.getString("age");
                
                
                
                //String datee=result.getString("Issued Date");

               id.setText(""+idd);
                fname.setText(name);
                lname.setText(quantity);
                age.setText(mfg);
                


                add.setVisible(false);
            }
            else{
                add.setVisible(true);

            }

            pst.close();
            result.close();
        } catch (SQLException ex) {
            Logger.getLogger(displaystudent.class.getName()).log(Level.SEVERE, null, ex);
        
                      
    }//GEN-LAST:event_jTable1MouseClicked

    }//GEN-LAST:event_jTable1MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(displaystudent.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(displaystudent.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(displaystudent.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(displaystudent.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new displaystudent().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton add;
    private javax.swing.JTextField age;
    private javax.swing.JButton delete;
    private javax.swing.JTextField fname;
    private javax.swing.JTextField id;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField lname;
    // End of variables declaration//GEN-END:variables
}
